version: '2'
services:
  web:
    image: shajalahamedcse/flask-kubernetes:v0.0.1
    ports:
      - "5000:5000"
    volumes:
      - /opt/docker-compose-mysql:/flask_app
    links:
      - db:mysql
    container_name: flask_web_1
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    container_name: flask_db_1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      
